import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap', // 'swap' ensures fallback font is used while Space Grotesk loads, minimizing layout shift
  variable: '--font-space-grotesk', // Optional: define a CSS variable
});

export const metadata: Metadata = {
  title: "Finance Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://www.w3schools.com/w3css/4/w3.css"
        />
      </head>
      <body
        className={spaceGrotesk.className}
      >
        {children}
      </body>
    </html>
  );
}
